### ISSUE TITLE
sometimes when clicking too fast on the theme thingy it breaks

### ISSUE THREAD

**Issue by HKGx** [TheClashster/theclashster.github.io#6]
as in title

steps to reproduce:
- spam click the checkbox

picrel: ![](https://i.imgur.com/EdQcQMf.png)

**Comment by aadibajpai** [comment]
@myfrom is there a viable solution to this? 🤔

**Comment by myfrom** [comment]
Why do people do this? 😂😭

But yeah, there should be a solution possible. I think disabling the switch during the transition and re-enabling after will be enough.

**Comment by aadibajpai** [comment]
> Why do people do this? 😂😭
> 
> But yeah, there should be a solution possible. I think disabling the switch during the transition and re-enabling after will be enough.

How to do that? 😭

**Comment by myfrom** [comment]
Did it in #7 and added a few comments to make the code cleaner. Sorry for the wait.

**Comment by aadibajpai** [comment]
> Did it in #7 and added a few comments to make the code cleaner. Sorry for the wait.

No worries, it's perfect!
